# Generated by Django 4.0.10 on 2023-10-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=2345, max_length=20, verbose_name='Broj mobitela'),
            preserve_default=False,
        ),
    ]
